# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureDevTestLabsCreateEnvironment@1
  inputs:
    ConnectedServiceName: 'dps-sp'
    EnvironmentName: 'dev'
    LabId: 'dps-eastus2-labs-sandbox'
    RepositoryId: 'azure-devtestlab'
    TemplateId: 'ServiceFabric-LabCluster'
    TemplateOutputVariables: false
    ExportEnvironmentTemplate: false